
import React, { useEffect, useState } from 'react'

import Layout from '@theme/Layout'
import DocSidebar from '@theme/DocSidebar'
import TOC from '@theme/TOC'
import TOCCollapsible from '@theme/TOCCollapsible'
import useWindowSize from '@theme/hooks/useWindowSize'

import { RedocStandalone } from 'redoc';
import useBaseUrl from '@docusaurus/useBaseUrl'
import styles from './styles.module.css'

import sidebarDefinition from './sidebars.json'
import tocDefinition from './toc.json'

const STATIC_SPEC = '/schema.yml'

/**
 * The HttpApi component renders a page for the HTTP API reference using Redoc.
 * To fit the Redoc layout into the rest of the site, it forced Redoc to render
 * the "mobile" layout with responses stacked inline, and it also hides the
 * default Redoc navigation pane. 
 * 
 * To replace the navigation pane, we generate a table of contents definition
 * from the OpenAPI schema and render a TOC component.
 * See /scripts/api-toc.js for the schema -> TOC code.
 * 
 */
function HttpApi() {
  const windowSize = useWindowSize()
  const [tocReady, setTocReady] = useState(false)

  const enableTocHighlights = () => {
    addAnchorClasses()
    setTocReady(true)
  }
  
  useEffect(() => {
    setTimeout(enableTocHighlights, 200)
  })

  const showDesktopToc = (windowSize === 'desktop' || windowSize === 'ssr')

  return (
    <Layout title="HTTP API reference | Web3.Storage Docs" 
      description="HTTP API Reference Docs for Web3.Storage">
        <div className={styles.container} >
          <div className={styles.sidebarWrapper}>
            <DocSidebar
              path='/http-api/'
              sidebar={sidebarDefinition.docs} 
            />
          </div>
          <div className={styles.redocWrapper} >
            <div className={styles.mobileTocWrapper} >
                <TOCCollapsible toc={tocDefinition} />
            </div>
            <RedocStandalone specUrl={useBaseUrl(STATIC_SPEC)} 
              options={{
                theme: {
                  sidebar: {
                    width: "0px"
                  },

                  // force "mobile" stacked layout at all breakpoints
                  breakpoints: {
                    small: '1rem',
                    medium: '100000rem',
                    large: '100000rem',
                  },
                  rightPanel: {
                    backgroundColor: '#3f3f75',
                  }
                }
              }} 
            />
          </div>
          { tocReady && showDesktopToc &&
            <div className={styles.tocWrapper}>
              <TOC toc={tocDefinition} />
            </div>
          }
        </div>
    </Layout>
  );
}

/**
 * Docusaurus looks for the css selector `.anchor.anchor__h2` when figuring
 * out which TOC anchor is "active" and should be highlighted.
 * 
 * This function finds the section headers generated by Redoc and adds the
 * magic classes, so the TOC component will find them.
 * 
 * Needs to be invoked a few ms after the Redoc component mounts, which is
 * why it's called in a setTimeout above.
 */
function addAnchorClasses() {
  const selector = 'div[data-section-id]'
  const divs = document.querySelectorAll(selector)
  for (const el of divs) {
    el.classList.add('anchor')
    el.classList.add('anchor__h2')
  }
}

export default HttpApi;